### ISSUE TITLE
Newcomer questions

### ISSUE THREAD

**Issue by nlooije** [blazedem/blazedemGPU#2]
Hi, 

I think the DEM framework you have build is awesome(!) but i have a couple of questions:

1. The Silo case seems to freeze my laptop (NV 765M) on initialization, but only while `Display: 1 0`, otherwise it runs. What can be the cause of this? Also when run only in command-line, no massflow is recorded, for all times `0` is written to file. It says the hatch is open in the command line.
2. How can I best visualize the particles? is there some option to output VTK at specified times and visualize with Paraview?
3. Just a general remark; while i appreciate all the work you have done it seems the framework is under-documented. Except for build instructions on the GH page, there is no mention of the different options or how to visualize. Some options are self-explanatory but others not so much, e.g. why is `Display: 1 0` what does the second integer represent? Another example `View: 0`, what does it do?

**Comment by blazedem** [comment]
Thank you for your feedback.

1. I have pushed the latest version to the repository. Can you confirm whether you still encounter the same issue.

2. The current output format can easily be converted to VTK using a Python script, we will upload this in the near future.

3. Thank you for your feedback, we are aware that the documentation needs to be included, we will update the documentation in due time. We are in the process of growing the BlazeDEM team to assist.

**Comment by blazedem** [comment]
Display: Param1 Param2 Param3
Param1 - 1 OpenGL display; 0 no display
Param2 - 0 Color Particles by Type; Color Particles by Velocity
Param3 - Velocity bin size colorer

View: Param1 
Param1 - 0 perspective view, 1 orthographic view

**Comment by nlooije** [comment]
Thanks for the swift reply.
1. The display issue is still present. It seems to be an issue with the opengl implementation because when i kill the process using `top` the command-line shows the visualization usage messages.
2. Do you have any ETA on the script? I wouldn't mind using an alpha/beta version for now if you have one.
3. If i can be of any help with the documentation, let me know...

**Comment by nlooije** [comment]
Regarding: 1. I ran the code on a Titan X and the Silo case works just fine; maybe i am running into the same bug as #https://github.com/blazedem/blazedemGPU/issues/1? Is that issue still relevant?
